#默认启动配置
spring.profiles.active: development.env


---
spring:
  profiles: development.env

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    #content-type: text/html
    mode: HTML5

  mvc.static-path-pattern: /static/**

server:
  port: 9000
  #context-path: /
